### ISSUE TITLE
010 Editor Template for .agstats (STAT file)

### ISSUE THREAD

**Issue by LordNed** [HandsomeMatt/botw-modding#4]
Whipped this one up tonight on a whim. Checked a fair chunk of the files and none of the asserts tripped, they may be version numbers or constants. Doesn't handle uncompressing the archive, or unzipping the archive.

Edits files found in /content/Game/Stats/archive

The map is broken up into a 10x8  (width:height) grid labeled A-J and 1-8 respectively. Each map section is broken up into four sub pieces in the form of "A-1.00", "A-1.01", "A-1.11", "A-1.10" (so all four combinations of two bits).

I don't have an automated way to decompress and de-archive and test these on all files.

```
// Forward Declare
struct Data;


typedef struct // Vector2
{
	float x; float y;
} Vector2 <read=Vector2Read, write=Vector2Write, bgcolor=0xe3adff>;

typedef struct // Header
{
    char signature[4]; // STAT
    uint16 Unknown1; // 1
    uint16 Unknown2; // 0
    uint16 Unknown3; // 0
    uint16 Unknown4; // 1
    uint32 HeaderSize; // 40
    Vector2 BoundsCenter;
    Vector2 BoundsBoxSize;
    uint32 SizeX; // 100
    uint32 SizeY; // 100

    Data FileData <open=true>;

    Assert(Unknown1 == 1, "Header Unknown1 isn't 1");
    Assert(Unknown2 == 0, "Header Unknown2 isn't 0");
    Assert(Unknown3 == 0, "Header Unknown3 isn't 0");
    Assert(Unknown4 == 1, "Header Unknown4 isn't 1");
} Header <bgcolor=0xCDFFFF>;

typedef struct // Data
{
    uint16 Unknown1; // 0

    enum <uint16> ElementTypes
	{
		Byte = 0,
        UnsignedByte = 8,
        Short = 4,
        UnsignedShort = 6,
        Int = 10
	} ElementType <format=decimal, bgcolor=0xb1ffad>;

    uint32 ElementCount; // 1
    uint16 Unknown2;
    uint16 Unknown3;
    uint32 DataTableSizePlus4;
    if(ElementType == 0)
    {
        byte DataTable[DataTableSizePlus4 - 4] <bgcolor=0xCFDEF2>;
    }
    else if(ElementType == 8)
    {
        // (byte and ubyte might have types swapped)
        ubyte DataTable[DataTableSizePlus4 - 4] <bgcolor=0xCFDEF2>;
    }
    else if(ElementType == 06)
    {    
        ushort DataTable[(DataTableSizePlus4-4)/2] <bgcolor=0xCFDEF2>;
    }
    else if(ElementType == 04)
    {
        // (short and ushort might have types swapped)
        short DataTable[(DataTableSizePlus4-4)/2] <bgcolor=0xCFDEF2>;
    }
    else if(ElementType == 10)
    {
        int DataTable[(DataTableSizePlus4-4)/4] <format=binary, bgcolor=0xCFDEF2>;
    }

    string Name;


    Assert(Unknown1 == 0, "Data Unknown1 isn't 0");
    Assert(Unknown2 == 0, "Data Unknown2 isn't 0");
    Assert(Unknown3 == 8, "Data Unknown3 isn't 8");
} Data <bgcolor=0x9ef442>; 

string Vector2Read(Vector2 &v)
{
	string s;
	SPrintf(s, "(%f, %f)", v.x, v.y);
	return s;
}
void Vector2Write(Vector2 &v, string s)
{
	SScanf(s, "(%f, %f)", v.x, v,y);
}

// ==== File Contents ==================================================================================================

BigEndian();
BitfieldRightToLeft();
Header file <open=true>;
```

**Comment by veryjos** [comment]
This is cool! Good job. Do you have any idea what this might be, speaking
from a high level? Maybe the markup information on the map screen?

**Comment by LordNed** [comment]
There are fourteen different stats for each section of map. They all store the same 100x100 resolution and bounding box, so I believe the game interpolates between the 100x100 points and blends between the closest set of four points to get a value for any given position.

autoplacement_forbid - 4 bytes per entry. Might be the auto-placement of grass/foliage/etc. It is unlikely the game stores each blade of grass's position and instead automatically populates them when you enter an area.
forest_density / forest_type - these probably specify how close foliage can spawn together for any given area, and what kind of foliage. 1 byte per entry for both.
material_map - May specify information about the underlying terrain surface (what hit effects to play, climbable vs not, not sure). 8 bytes each.
player_saftey_restart - presumably "positions it's okay to re-spawn you at when you fall off an infinite cliff/die/etc." 4 bytes each.
rock_distribution - see forest_density, 1 byte each.
route_distance - not sure. 2 bytes. Maybe some sort of distance field for your horse to know how to try and auto-merge onto paths? Doesn't specify individual paths though.
terrain_embedded_edge - no idea, 4 bytes each.
terrain_hidden - 4 bytes each. Probably a "patch" system that lets them skip generating triangles for a given section of heightmap terrain so that different meshes can be put in them (like inlets to caves and stuff).
terrain_is_in_door - I think this means "terrain_is_indoors" which could be considered true if there was traditional geometry modeling that made an overhang/etc. Might be for things like seeing if rain effects should play and if surface should get wet, etc.
water_depth - 2 bytes. Presumably controls the colors of the surface and not the actual depth. Maybe controls the height off of a given position that the water is?
water_distance - 2 bytes. Distance from edge maybe? 
water_flow - 1 byte. Not really enough data to be a direction (unless you count 4 bits each for x,y enough precision) unless it's a signed distance field, but that's not really a flow. Maybe it's for vertical surfaces for rain?
water_gradient - 1 byte each. See above, rivers push things down them automatically don't they?

@simply-jos I had a poke at your repositories - I'd try plotting these 100x100 fields stretched out to match the heightmap (or 1/4th the heightmap chunks, I forget how much land they cover) and see what they line up with and if the values start making sense.

**Comment by veryjos** [comment]
Good stuff.. Very interesting. Do you know if these files existed in the first release of the game? Are you looking at the latest version of the game?

The heightmap files come with a lot of other markup "heightmaps" that (we think) specify things like material, grass density, water height.. Some of them we are certain, other's we're not sure.

The interesting thing is that some of these markup heightmaps didn't exist in the 1.0 release and came later. My original hypothesis was that the markup info was originally stored on disk in other structures, and was derived, but that proved to be too costly and was causing the game to stutter. The focus of some of the updates was to stabilize performance, so splitting the info up into different markup heightmaps could ease up on IO. <- big leap in faith, but I have no clue why else they would have brought in those markup maps without adding extra info in the game

Could these have been the original, monolithic structures that used to be used? Because some of this information does seem redundant (material, grass density, forest type seem to be specified in the heightmaps), but I don't think the markup heightmaps contain _all_ of this information, so I'm unsure.

I'll definitely plot out these points with my tool and get back to you in some time.. Very busy for the next week or so.

**Comment by LordNed** [comment]
I'm on a fairly old version, pre-optimization updates I think. The cos.xml says Version 20, and App.xml says version 16, title version 0x21, sdk_version 21301.

I would be curious to know what they ended up changing for performance reasons between the two disks but haven't had the time/energy/thought to dump the disk again and look.

**Comment by LordNed** [comment]
Go figure, the version numbers don't seem to have changed. 

I looked at the latest version, this format is entirely gone as you suspected @simply-jos . They must have rolled it into other formats, perhaps for cache coherency. Oh well, knowing the format here in the old versions might help with RE'ing the modern one since the data is likely to be seen again.

**Comment by veryjos** [comment]
Oh, good find! Also, I'm not sure how the update logic works but do they actually remove files?

This is still really useful info, I plan on cross-referencing this info with the complementary heightmaps to glean some more information. Just the plaintext name like "water_flow" is insanely useful.

**Comment by LordNed** [comment]
The files are actually gone from the image, I assume consoles that update would do a delta diff with a manifest as part of the process. I searched the entire new disk image for "STAT" (the magic from this format) and there's only a dozen or so hits, mostly in the usage of "STATIC".

That being said, there are a *few* .hght.sstera's that have that the word "STAT" in them but a quick glance makes it look like coincidence and not the STAT file embedded inside the .hght file.
